# Generated by Django 4.2.30 on 2026-04-24 05:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('emergency', 'Emergency fund'), ('investing', 'Investing'), ('vacation', 'Vacation'), ('home', 'Home'), ('other', 'Other')], default='other', max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('target_date', models.DateField(blank=True, null=True)),
                ('basket_percent', models.DecimalField(decimal_places=2, default=0, help_text='Share of each deposit allocated to this goal (0–100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
