# Generated by Django 4.2.30 on 2026-04-28 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_account_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_personal', models.BooleanField(default=False, help_text='True for the auto-created Personal Space; only one per user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounts', models.ManyToManyField(blank=True, help_text="Per-account opt-in into this Space's combined view.", related_name='spaces', to='accounts.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='auth_app.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='spacemembership',
            constraint=models.UniqueConstraint(fields=('space', 'user'), name='auth_app_unique_space_member'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(condition=models.Q(('is_personal', True)), fields=('owner',), name='auth_app_one_personal_space_per_owner'),
        ),
    ]
