# Generated by Django 4.2.30 on 2026-04-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_savings_transfer',
            field=models.BooleanField(default=False, help_text="Flag when this row is one side of a transfer between your own accounts (e.g. checking → savings). Transfer rows are excluded from income/spending/savings math so the dashboard doesn't double-count them."),
        ),
    ]
